### ISSUE TITLE
ValueError: Unknown resampling filter (InterpolationMode.BICUBIC). 

### ISSUE THREAD

**Issue by JoyeeZhang** [YuvalNirkin/hyperseg#17]
**I have some problems when I train the model on my own data and I don't know if it is because that I make some mistakes when I load my data. 
Here are the details:**
Traceback (most recent call last):
  File "E:\zjy\hyperseg-main\hyperseg\train.py", line 254, in main
    epoch_loss, epoch_iou = proces_epoch(val_loader, train=False)
  File "E:\zjy\hyperseg-main\hyperseg\train.py", line 104, in proces_epoch
    for i, (input, target) in enumerate(pbar):
  File "E:\anaconda3\envs\zhangjiaying\lib\site-packages\tqdm\std.py", line 1130, in __iter__
    for obj in iterable:
  File "E:\anaconda3\envs\zhangjiaying\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "E:\anaconda3\envs\zhangjiaying\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "E:\anaconda3\envs\zhangjiaying\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "E:\anaconda3\envs\zhangjiaying\lib\site-packages\torch\_utils.py", line 438, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "E:\anaconda3\envs\zhangjiaying\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "E:\anaconda3\envs\zhangjiaying\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\anaconda3\envs\zhangjiaying\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\zjy\hyperseg-main\hyperseg\datasets\Massachusetts.py", line 104, in __getitem__
    img, target = self.transforms(img, target)
  File "E:\zjy\hyperseg-main\hyperseg\datasets\seg_transforms.py", line 78, in __call__
    input = list(t(*input))
  File "E:\zjy\hyperseg-main\hyperseg\datasets\seg_transforms.py", line 199, in __call__
    img = larger_edge_resize(img, self.size, self.interpolation)
  File "E:\zjy\hyperseg-main\hyperseg\datasets\seg_transforms.py", line 174, in larger_edge_resize
    return img.resize(size[::-1], interpolation)
  File "E:\anaconda3\envs\zhangjiaying\lib\site-packages\PIL\Image.py", line 1861, in resize
    raise ValueError(
ValueError: Unknown resampling filter (InterpolationMode.BICUBIC). Use Image.NEAREST (0), Image.LANCZOS (1), Image.BILINEAR (2), Image.BICUBIC (3), Image.BOX (4) or Image.HAMMING (5)

**Comment by JoyeeZhang** [comment]
And I don't calculate the weights of classes because the data just has two classes, building and no_building. I want to know that if it is necessary to calculate the weights.

**Comment by JoyeeZhang** [comment]
I found the same problems also appear when I train the model on data CamVid.

**Comment by jankin-wang** [comment]
have you solved this problem?  I met the same problem before the Original Traceback.

**Comment by JoyeeZhang** [comment]
I think maybe because of the version of your environment. I have solved this problem after I changed my environment.

**Comment by jankin-wang** [comment]
Thank you for your answer, but my code can run on another dataset. So I checked the current data set. Unfortunately, no problems were found.
It is strange that my original trace gave me the wrong code that had been run before and had no problems.Do you know why?

**Comment by JoyeeZhang** [comment]
Is the dataset you tried successfully given by the author? Or your own? And what about the dataset you cannot run?

**Comment by jankin-wang** [comment]
Thank you for your advice.It is truly the problem of my data set.I download my data set on GitHub and find that it is different from the official data set

**Comment by Haodong-Lei-Ray** [comment]
I use the dataset given by author. But the bug still occurs. I don't understand change what version of environment. Could you tell me more detail of your solution?

**Comment by YuvalNirkin** [comment]
I fixed this issue and added an exact environment installation yml.

**Comment by ZK1924** [comment]
> 

hello, can you tell me you  change which version of environment
