### ISSUE TITLE
Error in operation camvid_efficientnet_b1_hyperseg-s

### ISSUE THREAD

**Issue by zhang-pan** [YuvalNirkin/hyperseg#30]
Original Traceback (most recent call last):
  File "D:\Anaconda3\envs\hyperseg\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda3\envs\hyperseg\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\hyperseg\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\zhangpan\Desktop\论文集\尝试跑通-CVPR-2021-HyperSeg_ Patch-wise Hypernetwork for Real-time Semantic Segmentation\hyperseg-main\hyperseg\datasets\camvid.py", line 110, in __getitem__
    img, target = self.transforms(img, target)
  File "C:\Users\zhangpan\Desktop\论文集\尝试跑通-CVPR-2021-HyperSeg_ Patch-wise Hypernetwork for Real-time Semantic Segmentation\hyperseg-main\hyperseg\datasets\seg_transforms.py", line 51, in __call__
    input = list(t(*input))
  File "C:\Users\zhangpan\Desktop\论文集\尝试跑通-CVPR-2021-HyperSeg_ Patch-wise Hypernetwork for Real-time Semantic Segmentation\hyperseg-main\hyperseg\datasets\seg_transforms.py", line 172, in __call__
    img = larger_edge_resize(img, self.size, self.interpolation) ####################
  File "C:\Users\zhangpan\Desktop\论文集\尝试跑通-CVPR-2021-HyperSeg_ Patch-wise Hypernetwork for Real-time Semantic Segmentation\hyperseg-main\hyperseg\datasets\seg_transforms.py", line 147, in larger_edge_resize
    return img.resize(size[::-1], interpolation) ############################
  File "D:\Anaconda3\envs\hyperseg\lib\site-packages\PIL\Image.py", line 2070, in resize
    raise ValueError(ValueError: Unknown resampling filter (InterpolationMode.BICUBIC). Use Image.Resampling.NEAREST (0), Image.Resampling.LANCZOS (1), Image.Resampling.BILINEAR (2), Image.Resampling.BICUBIC (3), Image.Resampling.BOX (4) or Image.Resampling.HAMMING (5)

**Comment by YuvalNirkin** [comment]
Did you follow the installation instructions? What OS are you using?

**Comment by rouchoo** [comment]
I also have this problem. i have been try many times but could not address it. 
OS: ubuntu 22.04 ( cuda version: 11.4 ).
Please help me. Thanks.
