### ISSUE TITLE
Hi,please help me, 

### ISSUE THREAD

**Issue by ZzzTD** [YuvalNirkin/hyperseg#34]
When I load the checkpoint "cityscapes_efficientnet_b1_hyperseg-s.pth",there will be KeyError: 'optimizer'.

Traceback (most recent call last):
  File "D:/PyCharm Community Edition 2022.2.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm Community Edition 2022.2.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:\Pythonfiles\hyperseg-main\configs\train\cityscapes_efficientnet_b1_hyperseg-s.py", line 47, in <module>
    scheduler=scheduler, pretrained=pretrained, model=model, criterion=criterion, batch_scheduler=batch_scheduler)
  File "E:\Pythonfiles\hyperseg-main\hyperseg\train.py", line 227, in main
    optimizer.load_state_dict(checkpoint["optimizer"])
KeyError: 'optimizer'

thank you

**Comment by YuvalNirkin** [comment]
The provided checkpoints are only for evaluation, they can't be used to resume training (optimizer state was removed from checkpoint).

**Comment by ZzzTD** [comment]
@YuvalNirkin Thanks you !!!
