### ISSUE TITLE
python test.py

### ISSUE THREAD

**Issue by ZK1924** [YuvalNirkin/hyperseg#35]
python test.py 'checkpoints/vocsbd\vocsbd_efficientnet_b3_hyperseg-l' -td "hyperseg.datasets.voc_sbd.VOCSBDDataset('data/vocsbd',split='val',mode='fine')" -it "seg_transforms.Lar
gerEdgeResize([512,1024])"
Traceback (most recent call last):
  File "F:\22-lx\code\hyperseg-main\test.py", line 296, in <module>
    main(**vars(parser.parse_args()))
  File "F:\22-lx\code\hyperseg-main\test.py", line 117, in main
    assert os.path.isdir(exp_dir), f'exp_dir "{exp_dir}" must be a path to a directory'
AssertionError: exp_dir "'checkpoints/vocsbd\vocsbd_efficientnet_b3_hyperseg-l'" must be a path to a directory
can you help me?thankl you

**Comment by anizyu** [comment]
请问你解决了吗？怎么解决的？
